export enum SchoolAction {
  INVITE_MEMBER = 'INVITE_MEMBER',
  INVITE_ADMIN = 'INVITE_ADMIN',
  SUSPEND_MEMBER = 'SUSPEND_MEMBER',
  CANCEL_SUSPENSION = 'CANCEL_SUSPENSION',
  REVOKE_MEMBER = 'REVOKE_MEMBER',
  CHANGE_MEMBER_ROLE = 'CHANGE_MEMBER_ROLE',
  VIEW_MEMBERS = 'VIEW_MEMBERS',
  VIEW_MEMBER_DETAILS = 'VIEW_MEMBER_DETAILS',
  UPDATE_SCHOOL = 'UPDATE_SCHOOL',
  MANAGE_MEMBER_PERMISSIONS = 'MANAGE_MEMBER_PERMISSIONS',
}
