export enum AuditAction {
  SCHOOL_CREATED = 'SCHOOL_CREATED',
  SCHOOL_UPDATED = 'SCHOOL_UPDATED',
  SCHOOL_DELETED = 'SCHOOL_DELETED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  ADMINISTRATOR_INVITED = 'ADMINISTRATOR_INVITED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  ADMINISTRATOR_REPLACED = 'ADMINISTRATOR_REPLACED',
}
