import { UUID } from 'crypto';
import { SchoolStatus } from '../enums/school-status.enum.js';
import { InvalidSchoolException } from '../exceptions/invalid-school.exception.js';

export interface SchoolProps {
  id?: UUID;
  name: string;
  phoneNumber: string | null;
  email: string | null;
  website: string | null;
  status: SchoolStatus;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
}

export type NewSchool = Omit<SchoolProps, 'id'>;

export class School {
  private constructor(private props: SchoolProps) {}

  static create(input: {
    name: string;
    phoneNumber?: string | null;
    email?: string | null;
    website?: string | null;
    createdBy: string;
  }): School {
    const now = new Date();

    if (!Number.isFinite(now.getTime())) {
          throw new InvalidSchoolException('Invalid date');
    }

    if (!input.name?.trim()) {
          throw new InvalidSchoolException('School name is required');
    }

    if (!input.createdBy?.trim()) {
          throw new InvalidSchoolException('createdBy is required');
    }

    const props: SchoolProps = {
      id: undefined, // Will be generated by the database
      name: input.name.trim(),
      phoneNumber: input.phoneNumber?.trim() || null,
      email: input.email?.trim() || null,
      website: input.website?.trim() || null,
      status: SchoolStatus.ACTIVE,
      createdAt: new Date(now),
      updatedAt: new Date(now),
      createdBy: input.createdBy.trim(),
    };

    return new School(props);
  }

  static reconstitute(props: SchoolProps): School {
    return new School(structuredClone(props));
  }

  get id(): UUID | undefined {
    return this.props.id;
  }

  get name(): string {
    return this.props.name;
  }

  get status(): SchoolStatus {
    return this.props.status;
  }

  update(changes: {
    name?: string;
    phoneNumber?: string | null;
    email?: string | null;
    website?: string | null;
  }): void {
    if (changes.name !== undefined) {
      const name = changes.name.trim();
      if (!name) {
        throw new InvalidSchoolException('School name is required');
      }
      this.props.name = name;
    }

    if (changes.phoneNumber !== undefined) {
      this.props.phoneNumber = changes.phoneNumber?.trim() || null;
    }

    if (changes.email !== undefined) {
      this.props.email = changes.email?.trim() || null;
    }

    if (changes.website !== undefined) {
      this.props.website = changes.website?.trim() || null;
    }

    this.props.updatedAt = new Date();
  }

  updateStatus(newStatus: SchoolStatus): void {
    if (!Object.values(SchoolStatus).includes(newStatus)) {
          throw new InvalidSchoolException('Invalid school status');
    }
    this.props.status = newStatus;
    this.props.updatedAt = new Date();
  }

  block(): void {
    this.props.status = SchoolStatus.BLOCKED; 
    this.props.updatedAt = new Date();
  }
  
  unblock(): void {
    this.props.status = SchoolStatus.ACTIVE;
    this.props.updatedAt = new Date();
  }

  toPrimitives(): SchoolProps {
    return structuredClone(this.props);
  }
}