import { UUID } from 'crypto';
import { SchoolStatus } from '../enums/school-status.enum.js';
import { InvalidSchoolException } from '../exceptions/invalid-school.exception.js';

export interface SchoolProps {
  id?: UUID;
  name: string;
  phoneNumber: string | null;
  email: string | null;
  website: string | null;
  status: SchoolStatus;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
}

export type NewSchool = Omit<SchoolProps, 'id'>;

export interface SchoolDetailsChanges {
  name?: string;
  phoneNumber?: string | null;
  email?: string | null;
  website?: string | null;
}

export class School {
  private constructor(private props: SchoolProps) {}

  static create(input: {
    name: string;
    phoneNumber?: string | null;
    email?: string | null;
    website?: string | null;
    createdBy: string;
  }): School {
    const now = new Date();

    if (!Number.isFinite(now.getTime())) {
          throw new InvalidSchoolException('Invalid date');
    }

    if (!input.name?.trim()) {
          throw new InvalidSchoolException('School name is required');
    }

    if (!input.createdBy?.trim()) {
          throw new InvalidSchoolException('createdBy is required');
    }

    const props: SchoolProps = {
      id: undefined, // Will be generated by the database
      name: input.name.trim(),
      phoneNumber: input.phoneNumber?.trim() || null,
      email: input.email?.trim() || null,
      website: input.website?.trim() || null,
      status: SchoolStatus.ACTIVE,
      createdAt: new Date(now),
      updatedAt: new Date(now),
      createdBy: input.createdBy.trim(),
    };

    return new School(props);
  }

  static reconstitute(props: SchoolProps): School {
    return new School(structuredClone(props));
  }

  get id(): UUID | undefined {
    return this.props.id;
  }

  get name(): string {
    return this.props.name;
  }

  get status(): SchoolStatus {
    return this.props.status;
  }

  updateDetails(changes: SchoolDetailsChanges): void {
    const name = changes.name?.trim();
    if (changes.name !== undefined) {
      if (!name) {
        throw new InvalidSchoolException('School name is required');
      }
      if (name.length > 200) {
        throw new InvalidSchoolException('School name must not exceed 200 characters');
      }
    }
    const phoneNumber = changes.phoneNumber?.trim() || null;
    if (changes.phoneNumber !== undefined) {
      if (phoneNumber && phoneNumber.length > 50) {
        throw new InvalidSchoolException('Phone number must not exceed 50 characters');
      }
    }
    const email = changes.email?.trim() || null;
    if (changes.email !== undefined) {
      if (email && email.length > 320) {
        throw new InvalidSchoolException('Email must not exceed 320 characters');
      }
    }
    const website = changes.website?.trim() || null;
    if (changes.website !== undefined) {
      if (website && website.length > 500) {
        throw new InvalidSchoolException('Website must not exceed 500 characters');
      }
    }

    if (name !== undefined) this.props.name = name;
    if (changes.phoneNumber !== undefined) this.props.phoneNumber = phoneNumber;
    if (changes.email !== undefined) this.props.email = email;
    if (changes.website !== undefined) this.props.website = website;
    this.props.updatedAt = new Date();
  }

  updateStatus(newStatus: SchoolStatus): void {
    if (!Object.values(SchoolStatus).includes(newStatus)) {
          throw new InvalidSchoolException('Invalid school status');
    }
    if (this.props.status === newStatus) {
      return;
    }
    this.props.status = newStatus;
    this.props.updatedAt = new Date();
  }

  block(): void {
    this.props.status = SchoolStatus.BLOCKED; 
    this.props.updatedAt = new Date();
  }
  
  unblock(): void {
    this.props.status = SchoolStatus.ACTIVE;
    this.props.updatedAt = new Date();
  }

  toPrimitives(): SchoolProps {
    return structuredClone(this.props);
  }
}