import { UUID } from 'crypto';
import { SchoolStatus } from '../enums/school-status.enum.js';
import { InvalidSchoolException } from '../exceptions/invalid-school.exception.js';

export interface SchoolProps {
  id?: UUID;
  name: string;
  address: string | null;
  city: string | null;
  postalCode: string | null;
  country: string | null;
  phoneNumber: string | null;
  email: string | null;
  website: string | null;
  status: SchoolStatus;
  adminUserId: string | null;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
}

export type NewSchool = Omit<SchoolProps, 'id'>;

export class School {
  private constructor(private props: SchoolProps) {}

  static create(input: {
    name: string;
    address?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    website?: string | null;
    adminUserId?: string | null;
    createdBy: string;
  }): School {
    const now = new Date();

    if (!Number.isFinite(now.getTime())) {
          throw new InvalidSchoolException('Invalid date');
    }

    if (!input.name?.trim()) {
          throw new InvalidSchoolException('School name is required');
    }

    if (!input.createdBy?.trim()) {
          throw new InvalidSchoolException('createdBy is required');
    }

    const props: SchoolProps = {
      id: undefined, // Will be generated by the database
      name: input.name.trim(),
      address: input.address?.trim() || null,
      city: input.city?.trim() || null,
      postalCode: input.postalCode?.trim() || null,
      country: input.country?.trim() || null,
      phoneNumber: input.phoneNumber?.trim() || null,
      email: input.email?.trim() || null,
      website: input.website?.trim() || null,
      status: SchoolStatus.ACTIVE,
      adminUserId: input.adminUserId || null,
      createdAt: new Date(now),
      updatedAt: new Date(now),
      createdBy: input.createdBy.trim(),
    };

    return new School(props);
  }

  static reconstitute(props: SchoolProps): School {
    return new School(structuredClone(props));
  }

  get id(): UUID | undefined {
    return this.props.id;
  }

  get name(): string {
    return this.props.name;
  }

  get status(): SchoolStatus {
    return this.props.status;
  }

  get adminUserId(): string | null {
    return this.props.adminUserId;
  }

  update(changes: {
    name?: string;
    address?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    website?: string | null;
  }): void {
    if (changes.name !== undefined) {
      const name = changes.name.trim();
      if (!name) {
        throw new Error('School name is required');
      }
      this.props.name = name;
    }

    if (changes.address !== undefined) {
      this.props.address = changes.address?.trim() || null;
    }

    if (changes.city !== undefined) {
      this.props.city = changes.city?.trim() || null;
    }

    if (changes.postalCode !== undefined) {
      this.props.postalCode = changes.postalCode?.trim() || null;
    }

    if (changes.country !== undefined) {
      this.props.country = changes.country?.trim() || null;
    }

    if (changes.phoneNumber !== undefined) {
      this.props.phoneNumber = changes.phoneNumber?.trim() || null;
    }

    if (changes.email !== undefined) {
      this.props.email = changes.email?.trim() || null;
    }

    if (changes.website !== undefined) {
      this.props.website = changes.website?.trim() || null;
    }

    this.props.updatedAt = new Date();
  }

  updateStatus(newStatus: SchoolStatus): void {
    if (!Object.values(SchoolStatus).includes(newStatus)) {
          throw new InvalidSchoolException('Invalid school status');
    }
    this.props.status = newStatus;
    this.props.updatedAt = new Date();
  }

  // [AJOUT] Méthode pour bloquer l'école
  block(): void {
    this.props.status = SchoolStatus.BLOCKED; 
    this.props.updatedAt = new Date();
  }

  // [AJOUT] Méthode pour débloquer l'école
  unblock(): void {
    this.props.status = SchoolStatus.ACTIVE;
    this.props.updatedAt = new Date();
  }

  assignAdmin(adminUserId: string): void {
    if (!adminUserId?.trim()) {
          throw new InvalidSchoolException('Admin user ID is required');
    }
    this.props.adminUserId = adminUserId.trim();
    this.props.updatedAt = new Date();
  }

  removeAdmin(): void {
    this.props.adminUserId = null;
    this.props.updatedAt = new Date();
  }

  toPrimitives(): SchoolProps {
    return structuredClone(this.props);
  }
}